### ISSUE TITLE
TRACESWO output

### ISSUE THREAD

**Issue by ser9456** [openmv/openmv-boards#1]
Would it be possible to route TRACESWO line to the debug header (or if too difficult to where it's convenient)?
I understand it's not an essential line, but it may help during debugging.

**Comment by iabdalkader** [comment]
Will break it out to the debugging header. @ser9456 Do you recommend any debugger to read/decode the trace ?

**Comment by iabdalkader** [comment]
TRACESWO is now broken out to the debugging header on the latest rev.
