### ISSUE TITLE
May I ask if OPENMV4 PCB will be released?

### ISSUE THREAD

**Issue by HarryZeng** [openmv/openmv-boards#6]
May I ask if OPENMV4  PCB will be released?

**Comment by iabdalkader** [comment]
Yes, I'll add them.

**Comment by HarryZeng** [comment]
> Yes, I'll add them.

May I ask when?

**Comment by iabdalkader** [comment]
In a couple of days, maybe tomorrow.

**Comment by iabdalkader** [comment]
It's done.
