### ISSUE TITLE
sch 文件内容为空

### ISSUE THREAD

**Issue by xiaofangziLab** [openmv/openmv-boards#9]
sch 文件内容为空

**Comment by xiaofangziLab** [comment]
**### 原理图sch 文件下载下来 内容为空**

**Comment by Martyre-owl** [comment]
sch is empty

**Comment by iabdalkader** [comment]
Which one ? @Martyre-owl

**Comment by xiaofangziLab** [comment]
> Which one ? @Martyre-owl

All the *.sch file is empty  display nothing when opened by AltiumDesigner.

**Comment by iabdalkader** [comment]
@xiaofangziLab Those are Eagle files.
